a = input("Digite uma frase para descobrir seus tipos primitivos: \n")
print('sua classe é: ', type (a))
print('É um número:', a.isnumeric() )
print('É letra e número:', a.isalnum() )
print('É letra:', a.isalpha() )
print('Possui espaço:', a.isspace() )
print('Maiusculo:', a.isupper() )
print('Minusculo:', a.islower() )
print('É um título:', a.istitle() )
print('Printable: ', a.isprintable() )
print('Não começa com numeros e nem possui espaços:', a.isidentifier() )
print('Números sem espaços, letras ou pontuações:', a.isdigit() )
print('Número decimal:', a.isdecimal() )
print('letras, números, mas sem acentuações:', a.isascii() )